export type TypingDifficulty = 'easy' | 'normal' | 'hard';

export interface VocabularyNote {
  term: string;
  definition: string;
  translation: string;
  example: string;
}

export interface TypingPassage {
  id: string;
  difficulty: TypingDifficulty;
  topic: string;
  text: string;
  vocabulary?: VocabularyNote[];
}

const note = (term: string, definition: string, translation: string, example: string): VocabularyNote => ({ term, definition, translation, example });

export const TYPING_CURRICULUM: TypingPassage[] = [
  { id: 'easy-bus-stop', difficulty: 'easy', topic: 'daily life', text: 'I got to the bus stop early, so I had time to call my friend.', vocabulary: [note('got to', 'arrived at a place', '到達', 'We got to the movie theater just before the lights went down.'), note('had time to', 'was not too busy to do something', '有時間做某事', 'I had time to finish my homework before dinner.')] },
  { id: 'easy-school-club', difficulty: 'easy', topic: 'school', text: 'Our science club tried a new idea, and it worked better than we expected.', vocabulary: [note('tried out', 'tested something to see how it works', '試用、嘗試', 'We tried out the new robot after class.'), note('worked out', 'ended successfully', '順利成功', 'The plan worked out even though it looked difficult.')] },
  { id: 'easy-garden', difficulty: 'easy', topic: 'nature', text: 'The rain let up, and we went outside to look for tiny snails in the garden.', vocabulary: [note('let up', 'became less strong or stopped', '減弱、停下來', 'The wind finally let up after lunch.'), note('look for', 'try to find', '尋找', 'Can you look for my blue notebook?')] },
  { id: 'easy-game-night', difficulty: 'easy', topic: 'conversation', text: 'That sounds fun, but can we save the last round for tomorrow?', vocabulary: [note('sounds fun', 'seems enjoyable when you hear about it', '聽起來很好玩', 'Your camping trip sounds fun.'), note('save for', 'keep something for a later time', '留到以後', 'Let us save that puzzle for the weekend.')] },
  { id: 'normal-lab', difficulty: 'normal', topic: 'science', text: 'After a few false starts, the class figured out why the paper bridge kept folding in the middle.', vocabulary: [note('false start', 'an early attempt that does not work', '不成功的開端', 'My first sketch was a false start, but it gave me a better idea.'), note('figure out', 'understand or solve something', '弄懂、解決', 'We figured out how to make the model stronger.'), note('kept folding', 'continued to bend over again and again', '一直折彎', 'The cardboard kept folding until we added tape.')] },
  { id: 'normal-forest', difficulty: 'normal', topic: 'nature', text: 'We followed the trail until it opened onto a quiet clearing, where sunlight warmed the mossy ground.', vocabulary: [note('opened onto', 'led suddenly to a new place or view', '通向、豁然開到', 'The path opened onto a wide beach.'), note('clearing', 'an open space in a forest', '林中空地', 'We ate our snacks in a clearing between the trees.'), note('mossy', 'covered with soft green moss', '長滿苔蘚的', 'The rocks were damp and mossy after the rain.')] },
  { id: 'normal-tech', difficulty: 'normal', topic: 'technology', text: 'The app did not load at first, but restarting the tablet cleared up the problem right away.', vocabulary: [note('load', 'open and become ready to use', '載入', 'The video took a moment to load.'), note('clear up', 'solve or make something understandable', '解決、釐清', 'A quick update cleared up the login issue.'), note('right away', 'immediately', '立刻、馬上', 'Please tell me right away if you need help.')] },
  { id: 'normal-idea', difficulty: 'normal', topic: 'creativity', text: 'When our first design looked too crowded, we stepped back and gave the main idea more room to breathe.', vocabulary: [note('stepped back', 'paused to see a situation more clearly', '退一步重新看', 'We stepped back and noticed the missing piece.'), note('crowded', 'having too much in a small space', '擁擠、太滿', 'The poster felt crowded with so many colors.'), note('room to breathe', 'enough space to feel clear and comfortable', '留白、呼吸空間', 'The new layout gives the photos room to breathe.')] },
  { id: 'hard-conversation', difficulty: 'hard', topic: 'conversation', text: 'I was not sure I agreed at first, but once you put it that way, your suggestion makes a lot more sense.', vocabulary: [note('put it that way', 'express an idea in a particular manner', '用那種方式說', 'When you put it that way, the choice feels easier.'), note('makes sense', 'seems reasonable or understandable', '有道理', 'Your explanation makes sense to me now.'), note('at first', 'at the beginning', '一開始', 'At first, the new routine felt strange.')] },
  { id: 'hard-adventure', difficulty: 'hard', topic: 'adventure', text: 'By the time we reached the ridge, the fog had lifted enough for us to see the river winding through the valley below.', vocabulary: [note('by the time', 'when a particular later moment happens', '到…的時候', 'By the time we arrived, the show had started.'), note('ridge', 'a long narrow top of a hill or mountain', '山脊', 'We stopped on the ridge to watch the clouds move.'), note('winding', 'following a path with many turns', '蜿蜒的', 'A winding road led down to the village.')] },
  { id: 'hard-school', difficulty: 'hard', topic: 'school', text: 'Rather than rushing to finish, our teacher asked us to compare the evidence and explain which conclusion was best supported.', vocabulary: [note('rather than', 'instead of', '而不是', 'Rather than guess, let us check the instructions.'), note('evidence', 'facts that show something is true', '證據', 'The photos gave us evidence that the plant had grown.'), note('supported', 'shown to be likely or true by facts', '被支持、被證實', 'Her answer was supported by the data.')] },
  { id: 'hard-technology', difficulty: 'hard', topic: 'technology', text: 'The team narrowed down the bug by changing one setting at a time, which made the hidden pattern much easier to spot.', vocabulary: [note('narrow down', 'reduce a list of possibilities', '縮小範圍', 'We narrowed down the choices to two colors.'), note('bug', 'a mistake in a computer program', '程式錯誤', 'The developer fixed a bug in the game.'), note('spot', 'notice or see something', '發現、看出', 'Can you spot the difference between the two pictures?')] },
  { id: 'hard-policy', difficulty: 'hard', topic: 'society', text: 'The city introduced a congestion charge after a year-long study found that traffic delays were costing local businesses millions of dollars.', vocabulary: [note('congestion charge', 'a fee for driving in a crowded area', '交通壅塞費', 'The congestion charge encourages commuters to use public transport.'), note('year-long', 'continuing for an entire year', '持續一整年的', 'The team completed a year-long survey.'), note('costing', 'causing someone to lose money or resources', '使付出代價', 'The delay is costing the company valuable time.')] },
  { id: 'hard-research', difficulty: 'hard', topic: 'science', text: 'Although the findings are preliminary, they point to a promising connection between regular sleep and the brain\'s ability to consolidate new memories.', vocabulary: [note('preliminary', 'not final and likely to change', '初步的', 'The researchers released preliminary results.'), note('point to', 'suggest that something is likely', '指向、顯示', 'The evidence points to a change in customer habits.'), note('consolidate', 'make something stronger or more permanent', '鞏固、加深', 'Review helps students consolidate what they have learned.')] },
  { id: 'hard-remote-work', difficulty: 'hard', topic: 'technology', text: 'Remote work has made collaboration more flexible, but it also requires teams to be deliberate about documenting decisions that once happened informally.', vocabulary: [note('collaboration', 'the act of working together', '合作', 'The project depended on close collaboration between the two offices.'), note('be deliberate about', 'make a careful and intentional effort to do something', '刻意、審慎地做', 'We need to be deliberate about protecting customer data.'), note('informally', 'in a relaxed way without official structure', '非正式地', 'The two managers spoke informally after the meeting.')] },
  { id: 'hard-climate', difficulty: 'hard', topic: 'nature', text: 'Restoring wetlands can reduce the impact of flooding while creating habitats for wildlife, which is why conservation groups are urging municipalities to act.', vocabulary: [note('wetland', 'land covered or saturated with water', '濕地', 'The wetland provides shelter for migrating birds.'), note('habitat', 'the natural home of a plant or animal', '棲息地', 'The project protects a rare habitat.'), note('urge', 'strongly encourage someone to act', '敦促', 'Doctors urge people to stay hydrated during heat waves.')] },
  { id: 'hard-economy', difficulty: 'hard', topic: 'business', text: 'Rather than cutting staff immediately, the company froze new hiring and streamlined its supply chain to weather a period of uncertain demand.', vocabulary: [note('freeze hiring', 'temporarily stop employing new people', '暫停招募', 'The startup froze hiring until its next funding round.'), note('streamline', 'make a process simpler and more efficient', '精簡、使有效率', 'We streamlined the approval process.'), note('weather', 'successfully survive a difficult situation', '度過、撐過', 'Small businesses are trying to weather the downturn.')] },
  { id: 'hard-education', difficulty: 'hard', topic: 'school', text: 'Students tend to retain concepts more effectively when they explain an idea in their own words instead of merely memorizing a textbook definition.', vocabulary: [note('retain', 'keep information in your memory', '保留、記住', 'Short reviews help learners retain new vocabulary.'), note('in their own words', 'using personal language rather than repeating a source', '用自己的話', 'Explain the argument in your own words.'), note('merely', 'only; simply', '僅僅、只是', 'The task requires reasoning, not merely copying.')] },
  { id: 'hard-interview', difficulty: 'hard', topic: 'conversation', text: 'When asked about the setback, the candidate acknowledged what went wrong, then outlined the safeguards they had put in place to prevent a repeat.', vocabulary: [note('setback', 'a problem that delays progress', '挫折、阻礙', 'The unexpected repair was a temporary setback.'), note('acknowledge', 'accept or admit that something is true', '承認、確認', 'She acknowledged the concern before proposing a solution.'), note('put in place', 'establish or arrange something', '建立、落實', 'The school put new safety rules in place.')] },
  { id: 'hard-media', difficulty: 'hard', topic: 'conversation', text: 'It is easy for a headline to go viral before anyone checks the source, so readers should distinguish between a compelling claim and credible evidence.', vocabulary: [note('go viral', 'spread rapidly online', '在網路上快速傳播', 'The short video went viral overnight.'), note('distinguish between', 'recognize the difference between two things', '區分', 'Children should learn to distinguish between fact and opinion.'), note('credible', 'believable and trustworthy', '可信的', 'The report cites several credible sources.')] },
  { id: 'hard-innovation', difficulty: 'hard', topic: 'creativity', text: 'Innovation rarely follows a straight line; teams often make their biggest breakthrough after an unexpected failure exposes an assumption they had overlooked.', vocabulary: [note('straight line', 'a simple, direct path with no major changes', '直線、直接路徑', 'Career growth does not always follow a straight line.'), note('breakthrough', 'an important discovery or achievement', '突破', 'The experiment led to a scientific breakthrough.'), note('overlook', 'fail to notice something', '忽略、未注意到', 'We overlooked one detail in the contract.')] },
  { id: 'hard-ai', difficulty: 'hard', topic: 'technology', text: 'As artificial intelligence becomes easier to access, the most valuable skill may be knowing when a polished answer still requires careful human judgment.', vocabulary: [note('easier to access', 'more available for people to use', '更容易取得', 'Online courses have made expert advice easier to access.'), note('polished', 'well-presented and apparently complete', '精緻的、潤飾過的', 'The proposal sounded polished but lacked evidence.'), note('human judgment', 'a person\'s careful decision-making', '人的判斷力', 'Sensitive decisions still require human judgment.')] },
  { id: 'hard-ocean', difficulty: 'hard', topic: 'nature', text: 'Marine researchers are tracking changes in ocean temperature because even a small shift can disrupt migration patterns and affect an entire food chain.', vocabulary: [note('track', 'observe and record changes over time', '追蹤', 'Scientists track the storm as it moves offshore.'), note('disrupt', 'interrupt the normal progress of something', '擾亂、中斷', 'A missing part can disrupt the whole production line.'), note('food chain', 'the sequence of living things that feed on one another', '食物鏈', 'Plastic pollution can damage the marine food chain.')] },
  { id: 'hard-finance', difficulty: 'hard', topic: 'business', text: 'Investors responded cautiously to the quarterly report, noting that strong revenue growth was offset by rising operating costs and a weaker forecast.', vocabulary: [note('cautiously', 'in a careful way because of possible risks', '謹慎地', 'The board responded cautiously to the proposal.'), note('offset', 'balance or reduce the effect of something', '抵銷、平衡', 'Lower energy use offset part of the higher rent.'), note('forecast', 'a prediction about future events or results', '預測', 'The latest forecast suggests slower growth.')] },
  { id: 'hard-culture', difficulty: 'hard', topic: 'conversation', text: 'A thoughtful exchange does not require everyone to share the same opinion; it requires participants to listen closely enough to understand why they disagree.', vocabulary: [note('thoughtful', 'showing careful consideration', '深思熟慮的', 'She gave a thoughtful response to the criticism.'), note('exchange', 'a conversation or sharing of ideas', '交流', 'The conference encouraged an exchange of perspectives.'), note('disagree', 'have a different opinion', '不同意', 'It is possible to disagree without being disrespectful.')] },
  { id: 'hard-urban', difficulty: 'hard', topic: 'society', text: 'Well-designed public spaces can strengthen a neighborhood by giving residents a reason to linger, interact, and take pride in the place they share.', vocabulary: [note('linger', 'stay somewhere longer than necessary', '逗留', 'Visitors lingered in the square after the concert.'), note('residents', 'people who live in a place', '居民', 'Residents asked for safer crossings.'), note('take pride in', 'feel pleased about and responsible for something', '以…為榮', 'The volunteers take pride in keeping the park clean.')] },
  { id: 'hard-study', difficulty: 'hard', topic: 'school', text: 'Effective study is less about spending endless hours at a desk and more about alternating focused practice with enough rest for the brain to recover.', vocabulary: [note('endless', 'continuing without stopping or appearing to end', '無止境的', 'The endless notifications made it hard to focus.'), note('alternate', 'take turns between two activities or states', '交替', 'Alternate reading with short speaking practice.'), note('recover', 'return to a normal condition after effort', '恢復', 'The body needs time to recover after intense exercise.')] },
  { id: 'hard-space', difficulty: 'hard', topic: 'science', text: 'The telescope captured a faint signal from a distant galaxy, offering astronomers another clue about how massive structures formed in the early universe.', vocabulary: [note('faint', 'not strong, clear, or easy to see', '微弱的、模糊的', 'We heard a faint sound from the next room.'), note('distant', 'far away in space or time', '遙遠的', 'The mountain looked distant through the haze.'), note('formed', 'developed or came into existence', '形成', 'The mineral formed under extreme pressure.')] },
  { id: 'hard-ethics', difficulty: 'hard', topic: 'technology', text: 'Before deploying the update, the engineers tested how the system handled unusual requests, since reliability matters most when users cannot predict every scenario.', vocabulary: [note('deploy', 'put a system or product into active use', '部署、上線', 'The team will deploy the update tonight.'), note('unusual', 'different from what is common or expected', '不尋常的', 'The sensor detected unusual activity.'), note('reliability', 'the quality of working consistently well', '可靠性', 'Reliability is essential in medical equipment.')] },
  { id: 'hard-travel', difficulty: 'hard', topic: 'adventure', text: 'The guide warned us that the route was demanding, but the changing landscape made the long climb worthwhile once the valley came into view.', vocabulary: [note('demanding', 'requiring a lot of effort or skill', '要求高的、費力的', 'The course is demanding but rewarding.'), note('worthwhile', 'valuable enough to justify the effort', '值得的', 'The extra practice was worthwhile.'), note('came into view', 'became visible', '映入眼簾', 'The lighthouse came into view after the bend.')] },
  { id: 'hard-global', difficulty: 'hard', topic: 'society', text: 'International teams often move faster when they make expectations explicit, especially when a phrase that sounds polite in one culture may seem vague in another.', vocabulary: [note('make explicit', 'state something clearly rather than leaving it implied', '說清楚、明確化', 'The contract makes the delivery dates explicit.'), note('expectations', 'beliefs about what should happen', '期待、預期', 'Clear expectations prevent confusion.'), note('vague', 'not specific or clearly expressed', '模糊的', 'The instructions were too vague to follow.')] },
  { id: 'hard-evidence', difficulty: 'hard', topic: 'science', text: 'The review found no single explanation for the decline, but several independent studies pointed in the same direction and strengthened the overall case.', vocabulary: [note('independent', 'not controlled or influenced by another person or group', '獨立的', 'The claim was confirmed by an independent review.'), note('pointed in the same direction', 'gave similar evidence or suggestions', '指向相同方向', 'The interviews pointed in the same direction.'), note('overall case', 'the complete argument supported by available facts', '整體論據', 'The new data strengthens the overall case for reform.')] },
  { id: 'easy-morning-plan', difficulty: 'easy', topic: 'daily life', text: 'I wrote a short plan before breakfast, and the busy morning felt easier to manage.', vocabulary: [note('short plan', 'a brief list of things to do', '簡短計畫', 'I made a short plan for the weekend.'), note('manage', 'handle a task or situation', '處理、應付', 'She can manage the busy schedule.')] },
  { id: 'easy-helpful-question', difficulty: 'easy', topic: 'conversation', text: 'A helpful question can make a new classmate feel welcome on the first day.', vocabulary: [note('helpful', 'making something easier or better', '有幫助的', 'Your helpful advice solved the problem.'), note('feel welcome', 'feel accepted and comfortable', '感到受歡迎', 'The host made everyone feel welcome.')] },
  { id: 'easy-market-list', difficulty: 'easy', topic: 'daily life', text: 'We checked the shopping list twice before leaving for the market.', vocabulary: [note('check twice', 'look at something again to avoid a mistake', '檢查兩次', 'Check twice before you send the message.'), note('shopping list', 'a list of things to buy', '購物清單', 'I added apples to the shopping list.')] },
  { id: 'easy-team-turn', difficulty: 'easy', topic: 'school', text: 'Everyone took a turn, so the group finished the puzzle together.', vocabulary: [note('take a turn', 'do something after another person', '輪流', 'We take a turn reading each page.'), note('together', 'with one another as a group', '一起', 'The friends worked together.')] },
  { id: 'easy-raincoat', difficulty: 'easy', topic: 'nature', text: 'The clouds grew dark, so I packed a raincoat before walking home.', vocabulary: [note('grew dark', 'became less bright', '變暗', 'The sky grew dark before the storm.'), note('pack', 'put something into a bag for a trip', '收拾、打包', 'Remember to pack a jacket.')] },
  { id: 'easy-fix-it', difficulty: 'easy', topic: 'technology', text: 'The screen froze, but one quick restart helped the old phone work again.', vocabulary: [note('freeze', 'stop responding or moving', '當機、卡住', 'The game may freeze on an older device.'), note('restart', 'turn something off and on again', '重新啟動', 'Please restart the computer.')] },
  { id: 'normal-clear-message', difficulty: 'normal', topic: 'conversation', text: 'A clear message saves time because everyone knows what needs to happen next.', vocabulary: [note('save time', 'use less time than usual', '節省時間', 'A checklist can save time.'), note('what needs to happen', 'the action that is required', '需要發生的事', 'The team agreed on what needs to happen next.')] },
  { id: 'normal-small-business', difficulty: 'normal', topic: 'business', text: 'A small business can grow steadily when it listens to customers and improves one process at a time.', vocabulary: [note('steadily', 'in a regular and gradual way', '穩定地', 'The shop has grown steadily.'), note('one process at a time', 'improving steps gradually rather than all at once', '一次改善一個流程', 'We changed one process at a time.')] },
  { id: 'normal-travel-delay', difficulty: 'normal', topic: 'travel', text: 'When the train was delayed, the travelers checked the next connection instead of guessing the arrival time.', vocabulary: [note('delayed', 'made to happen later than planned', '延誤的', 'The flight was delayed by heavy rain.'), note('connection', 'a later vehicle or route that continues a journey', '轉乘班次', 'We have ten minutes to catch the connection.')] },
  { id: 'normal-reliable-source', difficulty: 'normal', topic: 'technology', text: 'Before sharing the story, Maya compared two reliable sources and checked when each page was updated.', vocabulary: [note('reliable', 'consistently accurate or dependable', '可靠的', 'Use a reliable source for the report.'), note('updated', 'changed with newer information', '更新的', 'The page was updated this morning.')] },
  { id: 'normal-project-scope', difficulty: 'normal', topic: 'creativity', text: 'The team narrowed the project scope so it could finish a useful first version before the deadline.', vocabulary: [note('narrow', 'make smaller or more limited', '縮小、收窄', 'We narrowed the search to three options.'), note('scope', 'the area or limits of a project', '範圍', 'The project scope is clear.')] },
  { id: 'normal-food-waste', difficulty: 'normal', topic: 'society', text: 'The café reduced food waste by tracking which dishes sold quickly and adjusting the menu each week.', vocabulary: [note('food waste', 'food that is thrown away instead of used', '食物浪費', 'The café is working to reduce food waste.'), note('adjust', 'change something slightly to improve it', '調整', 'We adjusted the menu for summer.')] },
  { id: 'normal-quiet-focus', difficulty: 'normal', topic: 'school', text: 'Short periods of quiet focus helped the students complete difficult work without feeling overwhelmed.', vocabulary: [note('period', 'a length of time', '一段時間', 'Take a short rest period.'), note('overwhelmed', 'feeling unable to manage everything', '不堪負荷的', 'She felt overwhelmed by the number of tasks.')] },
  { id: 'hard-payment-terms', difficulty: 'hard', topic: 'business', text: 'A promising order can still create pressure when payment terms delay cash collection longer than the supplier can comfortably finance.', vocabulary: [note('payment terms', 'the agreed rules for when and how payment is made', '付款條件', 'We reviewed the payment terms before signing.'), note('cash collection', 'the process of receiving money owed', '收款', 'Faster cash collection protects working capital.'), note('finance', 'provide or manage money for an activity', '提供資金、融資', 'The company cannot finance a long delay.')] },
  { id: 'hard-compare-options', difficulty: 'hard', topic: 'business', text: 'Comparing suppliers requires more than looking at the quoted price; lead time, quality evidence, and payment exposure can change the real commercial choice.', vocabulary: [note('quoted price', 'the price formally offered for a product or service', '報價', 'The quoted price excludes delivery.'), note('lead time', 'the time between ordering and receiving something', '交期', 'The lead time is six weeks.'), note('payment exposure', 'the amount of money placed at risk by payment timing or terms', '付款暴露', 'The deposit creates payment exposure.')] },
  { id: 'hard-decision-record', difficulty: 'hard', topic: 'technology', text: 'A decision record is most useful when it shows which evidence was known, which assumptions remained open, and who accepted the remaining uncertainty.', vocabulary: [note('assumption', 'something accepted as true without complete proof', '假設', 'The forecast depends on one assumption.'), note('remaining uncertainty', 'the part that is still not known or settled', '剩餘的不確定性', 'The review explains the remaining uncertainty.'), note('accepted', 'agreed to take or recognize something', '接受、承擔', 'The owner accepted the measured risk.')] },
  { id: 'hard-local-market', difficulty: 'hard', topic: 'society', text: 'Local companies often compete through responsiveness and trust, especially when customers value a dependable partner more than the lowest first quote.', vocabulary: [note('responsiveness', 'the ability to react quickly and helpfully', '回應能力', 'Responsiveness matters when schedules change.'), note('dependable', 'able to be trusted to do what is expected', '可靠的', 'The supplier is dependable.'), note('first quote', 'the initial price offered', '第一次報價', 'The first quote was not the final offer.')] },
  { id: 'hard-evidence-boundary', difficulty: 'hard', topic: 'technology', text: 'A polished summary should make the boundary of its evidence visible, because confidence in the writing cannot replace verification of the underlying facts.', vocabulary: [note('boundary', 'a limit that shows what is included or supported', '界線', 'The report states the evidence boundary.'), note('underlying', 'existing beneath or supporting something else', '底層的、背後的', 'We checked the underlying data.'), note('verification', 'the act of checking that something is true', '驗證', 'The claim requires independent verification.')] },
  { id: 'hard-customer-signal', difficulty: 'hard', topic: 'conversation', text: 'Interest is an encouraging signal, but a careful seller separates a friendly conversation from evidence that a buyer is ready to commit.', vocabulary: [note('encouraging', 'giving reason to feel hopeful', '令人鼓舞的', 'The early results are encouraging.'), note('separate A from B', 'recognize that two things are different', '區分 A 與 B', 'Separate interest from a firm order.'), note('commit', 'promise or decide to do something', '承諾', 'The buyer has not committed yet.')] },
  { id: 'hard-healthy-growth', difficulty: 'hard', topic: 'business', text: 'Healthy growth comes from repeatable work that creates value for customers without hiding the operational cost of every new promise.', vocabulary: [note('repeatable', 'able to be done successfully again', '可重複的', 'The team needs a repeatable process.'), note('operational cost', 'the cost of running and delivering the work', '營運成本', 'We included operational cost in the estimate.'), note('promise', 'a commitment that something will happen', '承諾', 'Every promise should have an owner.')] },
];

export const TIMED_TYPING_PASSAGE: TypingPassage = {
  id: 'timed-commercial-story',
  difficulty: 'normal',
  topic: 'business and everyday decisions',
  text: 'A good decision rarely begins with a perfect answer. It begins with a clear question, a careful look at the facts, and the courage to notice what is still unknown. Imagine a small team preparing to launch a new product. The idea is promising, customers have shown interest, and the first estimate looks profitable. It would be easy to move ahead immediately. Instead, the team pauses to check the details that could change the result. They ask who the real buyer is, what problem the product solves, when payment will arrive, and which costs are hidden inside delivery. They compare the first quotation with a second option, read the conditions line by line, and write down every assumption. Some answers are strong. Others are only suggestions from an early conversation. That difference matters. A friendly message is a useful signal, but it is not the same as a confirmed order. A forecast can guide planning, but it is not a commitment. A low price can look attractive, but the cheapest choice may require more cash, more time, or more risk. When the team makes these boundaries visible, discussion becomes easier. People can agree on what is known, challenge what is uncertain, and decide which evidence should come next. The purpose is not to remove every risk before taking action. The purpose is to choose the next action with open eyes. Sometimes the right move is to continue with a small, reversible test. Sometimes it is to ask the buyer for written terms, confirm the delivery point, or check the authority of the person making the request. Sometimes the responsible answer is to stop investing time until a serious concern is resolved. Clear records help the team learn from each outcome. They show why a decision was made, what changed later, and which early signal proved useful. Over time, this habit creates more than faster work. It creates better judgment. Whether the project is a school event, a local service, an international order, or a new software idea, the same discipline helps: understand the opportunity, separate evidence from assumption, protect the resources that matter, and leave room for a human decision.'
};

const LEGACY_PASSAGE_TEXTS = [
  'Small steps every day can build a skill that feels impossible at first.',
  'A curious mind asks questions, tries again, and learns from each mistake.',
  'The brightest ideas often begin with a quiet moment and an open notebook.',
  'Practice helps your fingers find the right keys without slowing your thoughts.',
  'A good game gives you one clear goal and a reason to play one more round.',
  'The little fox followed a silver trail through the quiet forest.',
  'Every morning, the birds sing while the sunlight reaches the garden.',
  'A brave explorer packs a map, a snack, and plenty of curiosity.',
  'The blue whale swims slowly beneath the waves and listens to the sea.',
  'After school, we can read a book, draw a picture, or build a new game.',
  'Good friends listen carefully, share their ideas, and help each other grow.',
  'The moon looks small from Earth, but it is a huge world in the night sky.',
  'A tiny seed needs water, sunlight, and time before it becomes a tall tree.',
  'Learning a new word is like finding another key to a secret door.',
  'The robot checked every button before starting its journey across Mars.',
  'Rain tapped softly on the window while the family played a board game.',
  'When the puzzle feels difficult, take a breath and try one piece at a time.',
  'The fastest player is not always the winner; careful choices matter too.',
  'Our class made paper rockets and tested which design could fly the farthest.',
  'Imagination can turn a cardboard box into a castle, a ship, or a spaceship.',
  'The sleepy panda climbed into the tree and found a cool place to rest.',
  'We watched orange clouds drift across the sky as the sun went down.',
  'The young chef mixed flour, eggs, and milk to make pancakes for breakfast.',
  'A friendly dog waited by the gate and wagged its tail when we came home.',
  'The library was quiet, but every book was filled with exciting adventures.',
  'Our team built a strong bridge by testing each idea and working together.',
  'The green turtle moved slowly across the sand toward the shining ocean.',
  'Music can make a rainy afternoon feel warm, bright, and full of energy.',
  'The astronaut looked through the window and saw Earth glowing far below.',
  'We planted colorful flowers so bees and butterflies could visit our yard.',
  'A clear plan makes a difficult project easier to understand and finish.',
  'The kitten chased a ball of yarn until it rolled beneath the wooden chair.',
  'Before crossing the road, stop at the corner and look in both directions.',
  'The mountain path was steep, so the hikers walked slowly and stayed together.',
  'A kind word can help someone feel stronger during a difficult day.',
  'The old clock rang at noon while people hurried through the busy town square.',
  'We used a flashlight to search the dark cave for sparkling stones.',
  'The soccer player passed the ball quickly and created space for the team.',
  'Reading every day can improve your vocabulary, focus, and imagination.',
  'The best inventions often begin when someone notices a simple problem.',
  'Mina folded a paper boat and sailed it across a puddle after the rain.',
  'The science club used magnets to discover which objects could move without touch.',
  'At the market, we chose sweet mangoes, crunchy carrots, and fresh bread.',
  'The owl stayed quiet on its branch until the stars appeared above the trees.',
  'A patient builder checks each block before adding the next part of a tower.',
  'The river carried tiny leaves past smooth rocks and under the old bridge.',
  'We made a list of questions before visiting the aquarium on Saturday.',
  'A map does not tell every answer, but it helps an explorer choose a direction.',
  'The baker smiled when the warm cinnamon rolls filled the kitchen with a sweet smell.',
  'During recess, the children invented a game with chalk lines and careful rules.',
  'A telescope helps us see distant planets that look like bright dots in the sky.',
  'The small drone rose gently above the field and took pictures of the corn rows.',
  'When the power went out, our family used candles and told funny stories together.',
  'The artist mixed blue and yellow paint until a bright green color appeared.',
  'A good question can lead to a new experiment, a new friend, or a new idea.',
  'The train arrived on time, and everyone hurried to find a window seat.',
  'We practiced tying knots so our camping tent would stay strong in the wind.',
  'The red bicycle had a bell that rang clearly along the quiet neighborhood street.',
  'A careful reader notices small clues that help solve a mystery before the last page.',
  'The gardener saved seeds from the tallest sunflowers for next spring.',
  'On a cold day, hot soup can make your hands and your heart feel warm.',
  'The inventor drew three different designs before choosing the simplest one to build.',
  'Our classroom calendar showed a field trip, a library day, and a music concert.',
  'The puppy learned to wait patiently before chasing the rolling tennis ball.',
  'A forest has many layers, from tiny mushrooms near the ground to tall treetops.',
  'The team listened to every idea and found a solution that no one had imagined alone.',
  'We watched the shadow of the flagpole grow longer as the afternoon became evening.',
  'A strong password keeps your favorite game and your private information safer.',
  'The moonlight made a silver path across the lake while frogs sang nearby.',
  'Before a big performance, take a slow breath and remember how much you practiced.',
];

export const LEGACY_TYPING_PASSAGES: TypingPassage[] = LEGACY_PASSAGE_TEXTS.map((text, index) => ({
  id: `legacy-${String(index + 1).padStart(2, '0')}`,
  difficulty: 'normal',
  topic: 'practice archive',
  text,
}));

export const TYPING_LIBRARY = [...TYPING_CURRICULUM, ...LEGACY_TYPING_PASSAGES];

export const DIFFICULTY_LABELS: Record<TypingDifficulty, string> = { easy: 'EASY', normal: 'NORMAL', hard: 'HARD' };

export function passagesForDifficulty(difficulty: TypingDifficulty) {
  return TYPING_LIBRARY.filter(passage => passage.difficulty === difficulty);
}

export function dailyPassage(dateKey: string) {
  let hash = 0;
  for (const character of dateKey) hash = (hash * 31 + character.charCodeAt(0)) >>> 0;
  return TYPING_CURRICULUM[hash % TYPING_CURRICULUM.length];
}
